### ISSUE TITLE
Setting's GUI lagging

### ISSUE THREAD

**Issue by YouFoundSci** [DataSynchronized/SyncAdmin#18]
Recently, the setting's GUI has been lagging to the point where the thing would not save the data you changed/set in it. This is an issue that needs to be fixed.

**Comment by YouFoundSci** [comment]
(I do understand that this might be an issue with my internet connection or my computer, but I was able to see the chat fine. There was no in-game lag other than the setting's panel lagging)

**Comment by Spearritt** [comment]
Hi,

Thank you for reporting this issue.
In order to get a more in depth understanding to what may be causing this issue, please could you send any outputs made by the developer console when you're in the Settings interface. Be sure to check both Client and Server log. 

I've also gone ahead and assigned the engineers to this for you.

**Comment by DataSynchronized** [comment]
Hey there @YouFoundSci 

We are aware that settings make take awhile to be sent to the server - especially if you have a long ban list, etc.

This is related to this issue: https://github.com/DataSynchronized/SyncAdmin/issues/2

We are working on the new backend server to better deal with settings changes from in-game. Our advice for the moment is to reduce the size of ban lists, admin lists, etc until we release the new build.

Thank you!
